// ================================================================
// NVDLA Open Source Project
// 
// Copyright(c) 2016 - 2017 NVIDIA Corporation.  Licensed under the
// NVDLA Open Hardware License; Check "LICENSE" which comes with 
// this distribution for more information.
// ================================================================

// Component: nvdla_top sc side SC-SV Adapter 
// This is autogenerated code

#ifndef _nvdla_top_sc_adapter_h
#define _nvdla_top_sc_adapter_h

#include "nvdla_scsv_sc_includes.h"

// Including nvdla_top specific headers
#ifndef __EDG__
#include "NV_nvdla.h"
#endif

// Including the socket converter headers
#include "nvdla_scsv_converter.h"

// Including nvdla_top layer headers
#include "nvdla_top_sc_layer.h"

// Including user specified headers

class nvdla_top_sc_adapter: public sc_module
{
 public:
    
    sc_out<bool > nvdla_top_sc2sv_nvdla_intr;  

#ifndef __EDG__
  //Instantiation of nvdla_top SystemC Module
  scsim::cmod::NV_nvdla *nvdla_top_sc_inst;

  //Instantiation of nvdla_top Layer Module
  nvdla_top_sc_layer *nvdla_top_sc_layer_inst; 
  
#endif

  //Constructor
  nvdla_top_sc_adapter(sc_module_name name);

};
#endif // nvdla_top_sc_adapter 

