// ================================================================
// NVDLA Open Source Project
// 
// Copyright(c) 2016 - 2017 NVIDIA Corporation.  Licensed under the
// NVDLA Open Hardware License; Check "LICENSE" which comes with 
// this distribution for more information.
// ================================================================

// nvdla_top sc side SC-SV Adapter 
// This is autogenerated code

#include "nvdla_top_sc_tlm_callbacks.h"

nvdla_top_sc2sv_nvdla_core2dbb_axi4_tlm_callbacks::nvdla_top_sc2sv_nvdla_core2dbb_axi4_tlm_callbacks(sc_module_name name):nvdla_scsv_sc_tlm_callbacks<tlm_generic_payload>(name){
    //Constructor
}
void nvdla_top_sc2sv_nvdla_core2dbb_axi4_tlm_callbacks::pre_btransport_cb(tlm_generic_payload &obj, sc_time &tlm_time){
    
}
void nvdla_top_sc2sv_nvdla_core2dbb_axi4_tlm_callbacks::post_btransport_cb(tlm_generic_payload &obj, sc_time &tlm_time){
    
}
                  
nvdla_top_sc2sv_nvdla_core2cvsram_axi4_tlm_callbacks::nvdla_top_sc2sv_nvdla_core2cvsram_axi4_tlm_callbacks(sc_module_name name):nvdla_scsv_sc_tlm_callbacks<tlm_generic_payload>(name){
    //Constructor
}
void nvdla_top_sc2sv_nvdla_core2cvsram_axi4_tlm_callbacks::pre_btransport_cb(tlm_generic_payload &obj, sc_time &tlm_time){
    
}
void nvdla_top_sc2sv_nvdla_core2cvsram_axi4_tlm_callbacks::post_btransport_cb(tlm_generic_payload &obj, sc_time &tlm_time){
    
}
                  
nvdla_top_sv2sc_nvdla_host_master_if_tlm_callbacks::nvdla_top_sv2sc_nvdla_host_master_if_tlm_callbacks(sc_module_name name):nvdla_scsv_sc_tlm_callbacks<tlm_generic_payload>(name){
    //Constructor
}
void nvdla_top_sv2sc_nvdla_host_master_if_tlm_callbacks::pre_btransport_cb(tlm_generic_payload &obj, sc_time &tlm_time){
    
}
void nvdla_top_sv2sc_nvdla_host_master_if_tlm_callbacks::post_btransport_cb(tlm_generic_payload &obj, sc_time &tlm_time){
    
}
                  
nvdla_top_sc2sv_dma_monitor_mc_tlm_callbacks::nvdla_top_sc2sv_dma_monitor_mc_tlm_callbacks(sc_module_name name):nvdla_scsv_sc_tlm_callbacks<tlm_generic_payload>(name){
    //Constructor
}
void nvdla_top_sc2sv_dma_monitor_mc_tlm_callbacks::pre_btransport_cb(tlm_generic_payload &obj, sc_time &tlm_time){
    
}
void nvdla_top_sc2sv_dma_monitor_mc_tlm_callbacks::post_btransport_cb(tlm_generic_payload &obj, sc_time &tlm_time){
    
}
                  
nvdla_top_sc2sv_dma_monitor_cv_tlm_callbacks::nvdla_top_sc2sv_dma_monitor_cv_tlm_callbacks(sc_module_name name):nvdla_scsv_sc_tlm_callbacks<tlm_generic_payload>(name){
    //Constructor
}
void nvdla_top_sc2sv_dma_monitor_cv_tlm_callbacks::pre_btransport_cb(tlm_generic_payload &obj, sc_time &tlm_time){
    
}
void nvdla_top_sc2sv_dma_monitor_cv_tlm_callbacks::post_btransport_cb(tlm_generic_payload &obj, sc_time &tlm_time){
    
}
                  
nvdla_top_sc2sv_convolution_core_monitor_initiator_tlm_callbacks::nvdla_top_sc2sv_convolution_core_monitor_initiator_tlm_callbacks(sc_module_name name):nvdla_scsv_sc_tlm_callbacks<tlm_generic_payload>(name){
    //Constructor
}
void nvdla_top_sc2sv_convolution_core_monitor_initiator_tlm_callbacks::pre_btransport_cb(tlm_generic_payload &obj, sc_time &tlm_time){
    
}
void nvdla_top_sc2sv_convolution_core_monitor_initiator_tlm_callbacks::post_btransport_cb(tlm_generic_payload &obj, sc_time &tlm_time){
    
}
                  
nvdla_top_sc2sv_post_processing_monitor_initiator_tlm_callbacks::nvdla_top_sc2sv_post_processing_monitor_initiator_tlm_callbacks(sc_module_name name):nvdla_scsv_sc_tlm_callbacks<tlm_generic_payload>(name){
    //Constructor
}
void nvdla_top_sc2sv_post_processing_monitor_initiator_tlm_callbacks::pre_btransport_cb(tlm_generic_payload &obj, sc_time &tlm_time){
    
}
void nvdla_top_sc2sv_post_processing_monitor_initiator_tlm_callbacks::post_btransport_cb(tlm_generic_payload &obj, sc_time &tlm_time){
    
}
                  
nvdla_top_sv2sc_dma_monitor_mc_credit_tlm_callbacks::nvdla_top_sv2sc_dma_monitor_mc_credit_tlm_callbacks(sc_module_name name):nvdla_scsv_sc_tlm_callbacks<tlm_generic_payload>(name){
    //Constructor
}
void nvdla_top_sv2sc_dma_monitor_mc_credit_tlm_callbacks::pre_btransport_cb(tlm_generic_payload &obj, sc_time &tlm_time){
    
}
void nvdla_top_sv2sc_dma_monitor_mc_credit_tlm_callbacks::post_btransport_cb(tlm_generic_payload &obj, sc_time &tlm_time){
    
}
                  
nvdla_top_sv2sc_dma_monitor_cv_credit_tlm_callbacks::nvdla_top_sv2sc_dma_monitor_cv_credit_tlm_callbacks(sc_module_name name):nvdla_scsv_sc_tlm_callbacks<tlm_generic_payload>(name){
    //Constructor
}
void nvdla_top_sv2sc_dma_monitor_cv_credit_tlm_callbacks::pre_btransport_cb(tlm_generic_payload &obj, sc_time &tlm_time){
    
}
void nvdla_top_sv2sc_dma_monitor_cv_credit_tlm_callbacks::post_btransport_cb(tlm_generic_payload &obj, sc_time &tlm_time){
    
}
                  
nvdla_top_sv2sc_convolution_core_monitor_credit_tlm_callbacks::nvdla_top_sv2sc_convolution_core_monitor_credit_tlm_callbacks(sc_module_name name):nvdla_scsv_sc_tlm_callbacks<tlm_generic_payload>(name){
    //Constructor
}
void nvdla_top_sv2sc_convolution_core_monitor_credit_tlm_callbacks::pre_btransport_cb(tlm_generic_payload &obj, sc_time &tlm_time){
    
}
void nvdla_top_sv2sc_convolution_core_monitor_credit_tlm_callbacks::post_btransport_cb(tlm_generic_payload &obj, sc_time &tlm_time){
    
}
                  
nvdla_top_sv2sc_post_processing_monitor_credit_tlm_callbacks::nvdla_top_sv2sc_post_processing_monitor_credit_tlm_callbacks(sc_module_name name):nvdla_scsv_sc_tlm_callbacks<tlm_generic_payload>(name){
    //Constructor
}
void nvdla_top_sv2sc_post_processing_monitor_credit_tlm_callbacks::pre_btransport_cb(tlm_generic_payload &obj, sc_time &tlm_time){
    
}
void nvdla_top_sv2sc_post_processing_monitor_credit_tlm_callbacks::post_btransport_cb(tlm_generic_payload &obj, sc_time &tlm_time){
    
}
