#!/bin/sh
if [ -d tests_256 ]
then
   echo "tests_256 exists"
else
   echo "cp -rp tests tests_256"
   cp -rp tests tests_256
fi

if [ -d tests_bd_256 ]
then
   echo "tests_bd_256 exists"
else
   echo "cp -rp  tests_bd  tests_bd_256"
   cp -rp tests_bd  tests_bd_256
fi

for var in `ls -1 tests`
   do
      echo "running: ../synth_tb/sim_scripts/inp_txn_to_hexdump.pl 32 tests/$var"
      ../synth_tb/sim_scripts/inp_txn_to_hexdump.pl 32 tests/$var
      mv *raw2 tests/$var
   done
for var in `ls -1 tests_bd`
   do
      echo "running: ../synth_tb/sim_scripts/inp_txn_to_hexdump.pl 32 tests_bd/$var"
      ../synth_tb/sim_scripts/inp_txn_to_hexdump.pl 32 tests_bd/$var
      mv *raw2 tests_bd/$var
   done
