../../vmod/nvdla/bdma/NV_NVDLA_BDMA_cq.v
../../vmod/nvdla/bdma/NV_NVDLA_BDMA_csb.v
../../vmod/nvdla/bdma/NV_NVDLA_BDMA_gate.v
../../vmod/nvdla/bdma/NV_NVDLA_BDMA_load.v
../../vmod/nvdla/bdma/NV_NVDLA_BDMA_reg.v
../../vmod/nvdla/bdma/NV_NVDLA_BDMA_store.v
../../vmod/nvdla/bdma/NV_NVDLA_bdma.v
../../vmod/nvdla/cacc/NV_NVDLA_CACC_CALC_fp_48b.v
../../vmod/nvdla/cacc/NV_NVDLA_CACC_CALC_int16.v
../../vmod/nvdla/cacc/NV_NVDLA_CACC_CALC_int8.v
../../vmod/nvdla/cacc/NV_NVDLA_CACC_assembly_buffer.v
../../vmod/nvdla/cacc/NV_NVDLA_CACC_assembly_ctrl.v
../../vmod/nvdla/cacc/NV_NVDLA_CACC_calculator.v
../../vmod/nvdla/cacc/NV_NVDLA_CACC_delivery_buffer.v
../../vmod/nvdla/cacc/NV_NVDLA_CACC_delivery_ctrl.v
../../vmod/nvdla/cacc/NV_NVDLA_CACC_dual_reg.v
../../vmod/nvdla/cacc/NV_NVDLA_CACC_regfile.v
../../vmod/nvdla/cacc/NV_NVDLA_CACC_single_reg.v
../../vmod/nvdla/cacc/NV_NVDLA_CACC_slcg.v
../../vmod/nvdla/cacc/NV_NVDLA_cacc.v
../../vmod/nvdla/car/NV_NVDLA_core_reset.v
../../vmod/nvdla/car/NV_NVDLA_reset.v
../../vmod/nvdla/car/NV_NVDLA_sync3d.v
../../vmod/nvdla/car/NV_NVDLA_sync3d_c.v
../../vmod/nvdla/car/NV_NVDLA_sync3d_s.v
../../vmod/nvdla/cbuf/NV_NVDLA_cbuf.v
../../vmod/nvdla/cdma/NV_NVDLA_CDMA_CVT_cell.v
../../vmod/nvdla/cdma/NV_NVDLA_CDMA_DC_fifo.v
../../vmod/nvdla/cdma/NV_NVDLA_CDMA_IMG_ctrl.v
../../vmod/nvdla/cdma/NV_NVDLA_CDMA_IMG_fifo.v
../../vmod/nvdla/cdma/NV_NVDLA_CDMA_IMG_pack.v
../../vmod/nvdla/cdma/NV_NVDLA_CDMA_IMG_sg.v
../../vmod/nvdla/cdma/NV_NVDLA_CDMA_IMG_sg2pack_fifo.v
../../vmod/nvdla/cdma/NV_NVDLA_CDMA_WG_fifo.v
../../vmod/nvdla/cdma/NV_NVDLA_CDMA_WT_fifo.v
../../vmod/nvdla/cdma/NV_NVDLA_CDMA_WT_sp_arb.v
../../vmod/nvdla/cdma/NV_NVDLA_CDMA_WT_wgs_fifo.v
../../vmod/nvdla/cdma/NV_NVDLA_CDMA_WT_wrr_arb.v
../../vmod/nvdla/cdma/NV_NVDLA_CDMA_cvt.v
../../vmod/nvdla/cdma/NV_NVDLA_CDMA_dc.v
../../vmod/nvdla/cdma/NV_NVDLA_CDMA_dma_mux.v
../../vmod/nvdla/cdma/NV_NVDLA_CDMA_dual_reg.v
../../vmod/nvdla/cdma/NV_NVDLA_CDMA_img.v
../../vmod/nvdla/cdma/NV_NVDLA_CDMA_regfile.v
../../vmod/nvdla/cdma/NV_NVDLA_CDMA_shared_buffer.v
../../vmod/nvdla/cdma/NV_NVDLA_CDMA_single_reg.v
../../vmod/nvdla/cdma/NV_NVDLA_CDMA_slcg.v
../../vmod/nvdla/cdma/NV_NVDLA_CDMA_status.v
../../vmod/nvdla/cdma/NV_NVDLA_CDMA_wg.v
../../vmod/nvdla/cdma/NV_NVDLA_CDMA_wt.v
../../vmod/nvdla/cdma/NV_NVDLA_cdma.v
../../vmod/nvdla/cdp/NV_NVDLA_CDP_DP_INTP_unit.v
../../vmod/nvdla/cdp/NV_NVDLA_CDP_DP_LUT_CTRL_unit.v
../../vmod/nvdla/cdp/NV_NVDLA_CDP_DP_LUT_ctrl.v
../../vmod/nvdla/cdp/NV_NVDLA_CDP_DP_MUL_unit.v
../../vmod/nvdla/cdp/NV_NVDLA_CDP_DP_bufferin.v
../../vmod/nvdla/cdp/NV_NVDLA_CDP_DP_cvtin.v
../../vmod/nvdla/cdp/NV_NVDLA_CDP_DP_cvtout.v
../../vmod/nvdla/cdp/NV_NVDLA_CDP_DP_intp.v
../../vmod/nvdla/cdp/NV_NVDLA_CDP_DP_lut.v
../../vmod/nvdla/cdp/NV_NVDLA_CDP_DP_mul.v
../../vmod/nvdla/cdp/NV_NVDLA_CDP_DP_nan.v
../../vmod/nvdla/cdp/NV_NVDLA_CDP_DP_sum.v
../../vmod/nvdla/cdp/NV_NVDLA_CDP_DP_syncfifo.v
../../vmod/nvdla/cdp/NV_NVDLA_CDP_RDMA_REG_dual.v
../../vmod/nvdla/cdp/NV_NVDLA_CDP_RDMA_REG_single.v
../../vmod/nvdla/cdp/NV_NVDLA_CDP_RDMA_cq.v
../../vmod/nvdla/cdp/NV_NVDLA_CDP_RDMA_eg.v
../../vmod/nvdla/cdp/NV_NVDLA_CDP_RDMA_ig.v
../../vmod/nvdla/cdp/NV_NVDLA_CDP_RDMA_reg.v
../../vmod/nvdla/cdp/NV_NVDLA_CDP_REG_dual.v
../../vmod/nvdla/cdp/NV_NVDLA_CDP_REG_single.v
../../vmod/nvdla/cdp/NV_NVDLA_CDP_dp.v
../../vmod/nvdla/cdp/NV_NVDLA_CDP_rdma.v
../../vmod/nvdla/cdp/NV_NVDLA_CDP_reg.v
../../vmod/nvdla/cdp/NV_NVDLA_CDP_slcg.v
../../vmod/nvdla/cdp/NV_NVDLA_CDP_wdma.v
../../vmod/nvdla/cdp/NV_NVDLA_cdp.v
../../vmod/nvdla/cdp/fp_format_cvt.v
../../vmod/nvdla/cdp/fp_sum_block.v
../../vmod/nvdla/cdp/int_sum_block.v
../../vmod/nvdla/cmac/NV_NVDLA_CMAC_CORE_MAC_exp.v
../../vmod/nvdla/cmac/NV_NVDLA_CMAC_CORE_MAC_mul.v
../../vmod/nvdla/cmac/NV_NVDLA_CMAC_CORE_MAC_nan.v
../../vmod/nvdla/cmac/NV_NVDLA_CMAC_CORE_active.v
../../vmod/nvdla/cmac/NV_NVDLA_CMAC_CORE_cfg.v
../../vmod/nvdla/cmac/NV_NVDLA_CMAC_CORE_mac.v
../../vmod/nvdla/cmac/NV_NVDLA_CMAC_CORE_rt_in.v
../../vmod/nvdla/cmac/NV_NVDLA_CMAC_CORE_rt_out.v
../../vmod/nvdla/cmac/NV_NVDLA_CMAC_CORE_slcg.v
../../vmod/nvdla/cmac/NV_NVDLA_CMAC_REG_dual.v
../../vmod/nvdla/cmac/NV_NVDLA_CMAC_REG_single.v
../../vmod/nvdla/cmac/NV_NVDLA_CMAC_core.v
../../vmod/nvdla/cmac/NV_NVDLA_CMAC_reg.v
../../vmod/nvdla/cmac/NV_NVDLA_cmac.v
../../vmod/nvdla/csc/NV_NVDLA_CSC_SG_dat_fifo.v
../../vmod/nvdla/csc/NV_NVDLA_CSC_SG_wt_fifo.v
../../vmod/nvdla/csc/NV_NVDLA_CSC_WL_dec.v
../../vmod/nvdla/csc/NV_NVDLA_CSC_dl.v
../../vmod/nvdla/csc/NV_NVDLA_CSC_dual_reg.v
../../vmod/nvdla/csc/NV_NVDLA_CSC_pra_cell.v
../../vmod/nvdla/csc/NV_NVDLA_CSC_regfile.v
../../vmod/nvdla/csc/NV_NVDLA_CSC_sg.v
../../vmod/nvdla/csc/NV_NVDLA_CSC_single_reg.v
../../vmod/nvdla/csc/NV_NVDLA_CSC_slcg.v
../../vmod/nvdla/csc/NV_NVDLA_CSC_wl.v
../../vmod/nvdla/csc/NV_NVDLA_csc.v
../../vmod/nvdla/glb/NV_NVDLA_GLB_CSB_reg.v
../../vmod/nvdla/glb/NV_NVDLA_GLB_csb.v
../../vmod/nvdla/glb/NV_NVDLA_GLB_fc.v
../../vmod/nvdla/glb/NV_NVDLA_GLB_ic.v
../../vmod/nvdla/glb/NV_NVDLA_glb.v
../../vmod/nvdla/nocif/NV_NVDLA_CVIF_CSB_reg.v
../../vmod/nvdla/nocif/NV_NVDLA_CVIF_READ_IG_arb.v
../../vmod/nvdla/nocif/NV_NVDLA_CVIF_READ_IG_bpt.v
../../vmod/nvdla/nocif/NV_NVDLA_CVIF_READ_IG_cvt.v
../../vmod/nvdla/nocif/NV_NVDLA_CVIF_READ_IG_spt.v
../../vmod/nvdla/nocif/NV_NVDLA_CVIF_READ_cq.v
../../vmod/nvdla/nocif/NV_NVDLA_CVIF_READ_eg.v
../../vmod/nvdla/nocif/NV_NVDLA_CVIF_READ_ig.v
../../vmod/nvdla/nocif/NV_NVDLA_CVIF_WRITE_IG_arb.v
../../vmod/nvdla/nocif/NV_NVDLA_CVIF_WRITE_IG_bpt.v
../../vmod/nvdla/nocif/NV_NVDLA_CVIF_WRITE_IG_cvt.v
../../vmod/nvdla/nocif/NV_NVDLA_CVIF_WRITE_IG_spt.v
../../vmod/nvdla/nocif/NV_NVDLA_CVIF_WRITE_cq.v
../../vmod/nvdla/nocif/NV_NVDLA_CVIF_WRITE_eg.v
../../vmod/nvdla/nocif/NV_NVDLA_CVIF_WRITE_ig.v
../../vmod/nvdla/nocif/NV_NVDLA_CVIF_csb.v
../../vmod/nvdla/nocif/NV_NVDLA_CVIF_read.v
../../vmod/nvdla/nocif/NV_NVDLA_CVIF_write.v
../../vmod/nvdla/nocif/NV_NVDLA_MCIF_CSB_reg.v
../../vmod/nvdla/nocif/NV_NVDLA_MCIF_READ_IG_arb.v
../../vmod/nvdla/nocif/NV_NVDLA_MCIF_READ_IG_bpt.v
../../vmod/nvdla/nocif/NV_NVDLA_MCIF_READ_IG_cvt.v
../../vmod/nvdla/nocif/NV_NVDLA_MCIF_READ_IG_spt.v
../../vmod/nvdla/nocif/NV_NVDLA_MCIF_READ_cq.v
../../vmod/nvdla/nocif/NV_NVDLA_MCIF_READ_eg.v
../../vmod/nvdla/nocif/NV_NVDLA_MCIF_READ_ig.v
../../vmod/nvdla/nocif/NV_NVDLA_MCIF_WRITE_IG_arb.v
../../vmod/nvdla/nocif/NV_NVDLA_MCIF_WRITE_IG_bpt.v
../../vmod/nvdla/nocif/NV_NVDLA_MCIF_WRITE_IG_cvt.v
../../vmod/nvdla/nocif/NV_NVDLA_MCIF_WRITE_IG_spt.v
../../vmod/nvdla/nocif/NV_NVDLA_MCIF_WRITE_cq.v
../../vmod/nvdla/nocif/NV_NVDLA_MCIF_WRITE_eg.v
../../vmod/nvdla/nocif/NV_NVDLA_MCIF_WRITE_ig.v
../../vmod/nvdla/nocif/NV_NVDLA_MCIF_csb.v
../../vmod/nvdla/nocif/NV_NVDLA_MCIF_read.v
../../vmod/nvdla/nocif/NV_NVDLA_MCIF_write.v
../../vmod/nvdla/nocif/NV_NVDLA_XXIF_libs.v
../../vmod/nvdla/nocif/NV_NVDLA_cvif.v
../../vmod/nvdla/nocif/NV_NVDLA_mcif.v
../../vmod/nvdla/pdp/NV_NVDLA_PDP_CORE_cal1d.v
../../vmod/nvdla/pdp/NV_NVDLA_PDP_CORE_cal2d.v
../../vmod/nvdla/pdp/NV_NVDLA_PDP_CORE_preproc.v
../../vmod/nvdla/pdp/NV_NVDLA_PDP_CORE_unit1d.v
../../vmod/nvdla/pdp/NV_NVDLA_PDP_RDMA_REG_dual.v
../../vmod/nvdla/pdp/NV_NVDLA_PDP_RDMA_REG_single.v
../../vmod/nvdla/pdp/NV_NVDLA_PDP_RDMA_cq.v
../../vmod/nvdla/pdp/NV_NVDLA_PDP_RDMA_eg.v
../../vmod/nvdla/pdp/NV_NVDLA_PDP_RDMA_ig.v
../../vmod/nvdla/pdp/NV_NVDLA_PDP_RDMA_reg.v
../../vmod/nvdla/pdp/NV_NVDLA_PDP_REG_dual.v
../../vmod/nvdla/pdp/NV_NVDLA_PDP_REG_single.v
../../vmod/nvdla/pdp/NV_NVDLA_PDP_WDMA_cmd.v
../../vmod/nvdla/pdp/NV_NVDLA_PDP_WDMA_dat.v
../../vmod/nvdla/pdp/NV_NVDLA_PDP_core.v
../../vmod/nvdla/pdp/NV_NVDLA_PDP_nan.v
../../vmod/nvdla/pdp/NV_NVDLA_PDP_rdma.v
../../vmod/nvdla/pdp/NV_NVDLA_PDP_reg.v
../../vmod/nvdla/pdp/NV_NVDLA_PDP_slcg.v
../../vmod/nvdla/pdp/NV_NVDLA_PDP_wdma.v
../../vmod/nvdla/pdp/NV_NVDLA_pdp.v
../../vmod/nvdla/pdp/cal1d_fp16_pool_sum.v
../../vmod/nvdla/pdp/fp16_4add.v
../../vmod/nvdla/retiming/NV_NVDLA_RT_cacc2glb.v
../../vmod/nvdla/retiming/NV_NVDLA_RT_cmac_a2cacc.v
../../vmod/nvdla/retiming/NV_NVDLA_RT_cmac_b2cacc.v
../../vmod/nvdla/retiming/NV_NVDLA_RT_csb2cacc.v
../../vmod/nvdla/retiming/NV_NVDLA_RT_csb2cmac.v
../../vmod/nvdla/retiming/NV_NVDLA_RT_csc2cmac_a.v
../../vmod/nvdla/retiming/NV_NVDLA_RT_csc2cmac_b.v
../../vmod/nvdla/rubik/NV_NVDLA_RUBIK_dma.v
../../vmod/nvdla/rubik/NV_NVDLA_RUBIK_dr2drc.v
../../vmod/nvdla/rubik/NV_NVDLA_RUBIK_dual_reg.v
../../vmod/nvdla/rubik/NV_NVDLA_RUBIK_fifo.v
../../vmod/nvdla/rubik/NV_NVDLA_RUBIK_intr.v
../../vmod/nvdla/rubik/NV_NVDLA_RUBIK_regfile.v
../../vmod/nvdla/rubik/NV_NVDLA_RUBIK_rf_core.v
../../vmod/nvdla/rubik/NV_NVDLA_RUBIK_rf_ctrl.v
../../vmod/nvdla/rubik/NV_NVDLA_RUBIK_rf_rcmd.v
../../vmod/nvdla/rubik/NV_NVDLA_RUBIK_rf_wcmd.v
../../vmod/nvdla/rubik/NV_NVDLA_RUBIK_seq_gen.v
../../vmod/nvdla/rubik/NV_NVDLA_RUBIK_single_reg.v
../../vmod/nvdla/rubik/NV_NVDLA_RUBIK_slcg.v
../../vmod/nvdla/rubik/NV_NVDLA_RUBIK_wr_req.v
../../vmod/nvdla/rubik/NV_NVDLA_RUBIK_wrdma_cmd.v
../../vmod/nvdla/rubik/NV_NVDLA_RUBIK_wrdma_data.v
../../vmod/nvdla/rubik/NV_NVDLA_rubik.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_BRDMA_EG_ro.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_BRDMA_cq.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_BRDMA_eg.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_BRDMA_gate.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_BRDMA_ig.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_CORE_Y_core.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_CORE_Y_cvt.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_CORE_Y_dmapack.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_CORE_Y_dppack.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_CORE_Y_dpunpack.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_CORE_Y_idx.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_CORE_Y_inp.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_CORE_Y_lut.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_CORE_c.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_CORE_gate.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_CORE_x.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_CORE_y.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_ERDMA_EG_ro.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_ERDMA_cq.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_ERDMA_eg.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_ERDMA_gate.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_ERDMA_ig.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_MRDMA_EG_cmd.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_MRDMA_EG_din.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_MRDMA_EG_dout.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_MRDMA_cq.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_MRDMA_eg.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_MRDMA_gate.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_MRDMA_ig.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_NRDMA_EG_ro.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_NRDMA_cq.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_NRDMA_eg.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_NRDMA_gate.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_NRDMA_ig.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_RDMA_REG_dual.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_RDMA_REG_single.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_RDMA_reg.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_REG_dual.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_REG_single.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_WDMA_DAT_in.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_WDMA_DAT_out.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_WDMA_cmd.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_WDMA_dat.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_WDMA_dmaif.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_WDMA_gate.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_brdma.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_cmux.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_core.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_erdma.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_mrdma.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_nrdma.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_rdma.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_reg.v
../../vmod/nvdla/sdp/NV_NVDLA_SDP_wdma.v
../../vmod/nvdla/sdp/NV_NVDLA_sdp.v
../../vmod/nvdla/top/NV_NVDLA_partition_a.v
../../vmod/nvdla/top/NV_NVDLA_partition_c.v
../../vmod/nvdla/top/NV_NVDLA_partition_m.v
../../vmod/nvdla/top/NV_NVDLA_partition_o.v
../../vmod/nvdla/top/NV_NVDLA_partition_p.v
../../vmod/nvdla/top/NV_nvdla.v
../../vmod/nvdla/csb_master/NV_NVDLA_csb_master.v
../../vmod/nvdla/csb_master/NV_NVDLA_CSB_MASTER_csb2falcon_fifo.v
../../vmod/nvdla/csb_master/NV_NVDLA_CSB_MASTER_falcon2csb_fifo.v
../../vmod/vlibs/RANDFUNC.vlib
../../vmod/vlibs/nv_assert_no_x.vlib
../../vmod/include/simulate_x_tick.vh
-y ../../vmod/rams/synth
-y ../../vmod/rams/model
