# ============================================================================
#  @(#) $Id: Makefile.uvmc_sysc_standalone_vista 1413 2015-03-05 21:50:29Z jstickle $
# ============================================================================

#    //_______________________
#   // Mentor Graphics, Corp. \_______________________________________
#  //                                                               //
# //   (C) Copyright, Mentor Graphics, Corp. 2003-2014              //
# //   All Rights Reserved                                          //
# //                                                                //
# //    Licensed under the Apache License, Version 2.0 (the         //
# //    "License"); you may not use this file except in             //
# //    compliance with the License.  You may obtain a copy of      //
# //    the License at                                              //
# //                                                                //
# //        http://www.apache.org/licenses/LICENSE-2.0              //
# //                                                                //
# //    Unless required by applicable law or agreed to in           //
# //    writing, software distributed under the License is          //
# //    distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR      //
# //    CONDITIONS OF ANY KIND, either express or implied.  See     //
# //    the License for the specific language governing            //
# //    permissions and limitations under the License.            //
# //-------------------------------------------------------------//

# This Makefile adds support for an OSCI SystemC version of UVM-Connect SC for
# uses with a non-Questa OSCI SystemC kernel. See comments in
# Makefile.uvmc_sysc_standalone for more details.

all: build

BITS ?= 64

include common.mk

CXX="vista_c++ -m$(MTI_VCO_MODE)"
LIB = ../lib
LIBOBJ = $(LIB)/vista/$(UVMC_BUILD_PLATFORM)

INCL += \
    -I$(MTI_HOME)/include -I$(UVM_HOME)/src/dpi

build: $(LIBOBJ)/uvmc.build_imprint
	$(MAKE) -f Makefile.uvmc_sysc_standalone build \
		LIBOBJ="$(LIBOBJ)" CXX=$(CXX) INCL="$(INCL)"

$(LIBOBJ)/uvmc.build_imprint:
	mkdir -p $(LIBOBJ)
	BITS=$(BITS); export BITS; perl ../examples/common/xlcheck.pl env_vista | grep vista
	BITS=$(BITS); export BITS; perl ../examples/common/xlcheck.pl env_gcc | grep gcc
	BITS=$(BITS); export BITS; perl ../examples/common/xlcheck.pl env_vista | grep vista > $@
	BITS=$(BITS); export BITS; perl ../examples/common/xlcheck.pl env_gcc | grep gcc >> $@

clean:
	$(MAKE) -f Makefile.uvmc_sysc_standalone clean \
		LIBOBJ="$(LIBOBJ)" CXX=$(CXX) INCL="$(INCL)"
