-I../../outdir/nv_full/vmod/nvdla/bdma
-I../../outdir/nv_full/vmod/nvdla/cacc
-I../../outdir/nv_full/vmod/nvdla/car
-I../../outdir/nv_full/vmod/nvdla/cbuf
-I../../outdir/nv_full/vmod/nvdla/cdma
-I../../outdir/nv_full/vmod/nvdla/cdp
-I../../outdir/nv_full/vmod/nvdla/cmac
-I../../outdir/nv_full/vmod/nvdla/csc
-I../../outdir/nv_full/vmod/nvdla/glb
-I../../outdir/nv_full/vmod/nvdla/nocif
-I../../outdir/nv_full/vmod/nvdla/pdp
-I../../outdir/nv_full/vmod/nvdla/retiming
-I../../outdir/nv_full/vmod/nvdla/rubik
-I../../outdir/nv_full/vmod/nvdla/sdp
-I../../outdir/nv_full/vmod/nvdla/top
-I../../outdir/nv_full/vmod/nvdla/csb_master
-I../../outdir/nv_full/vmod/rams/synth
-I../../outdir/nv_full/vmod/vlibs
-I../../outdir/nv_full/vmod/include
-v ../../outdir/nv_full/vmod/vlibs/RANDFUNC.vlib
-v ../../outdir/nv_full/vmod/vlibs/nv_assert_no_x.vlib
-v ../../outdir/nv_full/vmod/nvdla/nocif/NV_NVDLA_XXIF_libs.v
-v ../../outdir/nv_full/vmod/rams/model/RAMPDP_248X82_GL_M2_D2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMPDP_32X192_GL_M1_D2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMPDP_32X224_GL_M1_D2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMPDP_256X80_GL_M2_D2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMPDP_80X256_GL_M1_D2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMPDP_160X82_GL_M2_D2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMPDP_80X226_GL_M1_D2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMPDP_256X144_GL_M2_D2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMPDP_32X288_GL_M1_D2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMPDP_32X256_GL_M1_D2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMDP_20X288_GL_M1_E2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMPDP_248X144_GL_M2_D2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMDP_80X15_GL_M2_E2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMPDP_60X168_GL_M1_D2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMDP_20X80_GL_M1_E2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMPDP_64X226_GL_M1_D2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMPDP_64X288_GL_M1_D2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMDP_32X32_GL_M1_E2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMDP_128X6_GL_M2_E2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMDP_128X11_GL_M2_E2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMDP_64X10_GL_M2_E2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMDP_16X256_GL_M1_E2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMPDP_80X72_GL_M1_D2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMDP_256X4_GL_M2_E2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMDP_256X7_GL_M2_E2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMDP_256X8_GL_M2_E2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMPDP_64X116_GL_M1_D2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMDP_32X16_GL_M1_E2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMPDP_256X11_GL_M4_D2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMPDP_160X16_GL_M2_D2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMDP_80X14_GL_M2_E2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMPDP_80X16_GL_M2_D2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMPDP_160X144_GL_M2_D2.v
-v ../../outdir/nv_full/vmod/rams/model/RAMPDP_80X288_GL_M1_D2.v
-DNO_PLI_OR_EMU
-DNO_PLI
-DDESIGNWARE_NOEXIST
-DSYNTHESIS
-Wno-moddup
-Wno-fatal
--top-module NV_nvdla
../../outdir/nv_full/vmod/nvdla/top/NV_nvdla.v
