// ================================================================
// NVDLA Open Source Project
// 
// Copyright(c) 2016 - 2017 NVIDIA Corporation.  Licensed under the
// NVDLA Open Hardware License; Check "LICENSE" which comes with 
// this distribution for more information.
// ================================================================

// File Name: nvdla_config.h
#ifndef __NVDLA_CONFIG__
#define __NVDLA_CONFIG__

#include "project.h"

#define NVDLA_FEATURE_DATA_TYPE_BINARY  (1<<0)
#define NVDLA_FEATURE_DATA_TYPE_UINT4   (1<<1)
#define NVDLA_FEATURE_DATA_TYPE_INT4    (1<<2)
#define NVDLA_FEATURE_DATA_TYPE_UINT8   (1<<3)
//#define NVDLA_FEATURE_DATA_TYPE_INT8    (1<<4)
#define NVDLA_FEATURE_DATA_TYPE_UINT16  (1<<5)
#define NVDLA_FEATURE_DATA_TYPE_INT16   (1<<6)
#define NVDLA_FEATURE_DATA_TYPE_UINT32  (1<<7)
#define NVDLA_FEATURE_DATA_TYPE_INT32   (1<<8)
#define NVDLA_FEATURE_DATA_TYPE_FP16    (1<<9)
#define NVDLA_FEATURE_DATA_TYPE_FP32    (1<<10)
#define NVDLA_FEATURE_DATA_TYPE_FP64    (1<<11)

#define NVDLA_WEIGHT_DATA_TYPE_BINARY   (1<<0)
#define NVDLA_WEIGHT_DATA_TYPE_UINT4    (1<<1)
#define NVDLA_WEIGHT_DATA_TYPE_INT4     (1<<2)
#define NVDLA_WEIGHT_DATA_TYPE_UINT8    (1<<3)
//#define NVDLA_WEIGHT_DATA_TYPE_INT8     (1<<4)
#define NVDLA_WEIGHT_DATA_TYPE_UINT16   (1<<5)
#define NVDLA_WEIGHT_DATA_TYPE_INT16    (1<<6)
#define NVDLA_WEIGHT_DATA_TYPE_UINT32   (1<<7)
#define NVDLA_WEIGHT_DATA_TYPE_INT32    (1<<8)
#define NVDLA_WEIGHT_DATA_TYPE_FP16     (1<<9)
#define NVDLA_WEIGHT_DATA_TYPE_FP32     (1<<10)
#define NVDLA_WEIGHT_DATA_TYPE_FP64     (1<<11)


#define MAX(a, b)       (a > b ? a:b)
#define MAX3(a, b, c)   (MAX(MAX(a, b), c))
#define MIN(a, b)       (a < b ? a:b)
#define MIN3(a, b, c)   (MIN(MIN(a, b), c))


#define PRIMARY_MEMIF_WIDTH     (NVDLA_PRIMARY_MEMIF_WIDTH/8)
#ifndef NVDLA_SECONDARY_MEMIF_MAX_BURST_LENGTH
#define NVDLA_SECONDARY_MEMIF_WIDTH                 NVDLA_PRIMARY_MEMIF_WIDTH
#define NVDLA_SECONDARY_MEMIF_MAX_BURST_LENGTH      NVDLA_PRIMARY_MEMIF_MAX_BURST_LENGTH
#endif
#define SECONDARY_MEMIF_WIDTH   (NVDLA_SECONDARY_MEMIF_WIDTH/8)
#ifdef NVDLA_FEATURE_DATA_TYPE_INT8
#define DLA_ATOM_SIZE           (NVDLA_MEMORY_ATOMIC_SIZE)
#else
#define DLA_ATOM_SIZE           (NVDLA_MEMORY_ATOMIC_SIZE*2)
#endif

#define MAX_MEM_TRANSACTION_SIZE  MAX(PRIMARY_MEMIF_WIDTH*NVDLA_PRIMARY_MEMIF_MAX_BURST_LENGTH, SECONDARY_MEMIF_WIDTH*NVDLA_SECONDARY_MEMIF_MAX_BURST_LENGTH)
#define DMAIF_WIDTH             MAX3(DLA_ATOM_SIZE, PRIMARY_MEMIF_WIDTH, SECONDARY_MEMIF_WIDTH)
#define MEMIF_ADDR_WIDTH        64
#define MIN_BUS_WIDTH           MIN3(DLA_ATOM_SIZE, PRIMARY_MEMIF_WIDTH, SECONDARY_MEMIF_WIDTH)

#ifndef NVDLA_SDP_BS_THROUGHPUT
#define NVDLA_SDP_BS_THROUGHPUT 0
#endif
#ifndef NVDLA_SDP_BN_THROUGHPUT
#define NVDLA_SDP_BN_THROUGHPUT 0
#endif
#ifndef NVDLA_SDP_EW_THROUGHPUT
#define NVDLA_SDP_EW_THROUGHPUT 0
#endif
#define SDP_MAX_THROUGHPUT      MAX3(NVDLA_SDP_BS_THROUGHPUT, NVDLA_SDP_BN_THROUGHPUT, NVDLA_SDP_EW_THROUGHPUT)


#endif
