#ifndef NVDLA_PROT_SCSV_REGISTER_EXTENSION_PACKER_DEFINES_
#define NVDLA_PROT_SCSV_REGISTER_EXTENSION_PACKER_DEFINES_

typedef enum NVDLA_SCSV_EXTENSION_PACKER_ENUM {
    NVDLA_DBB_SCSV_EXTENSION_PACKER_ID = 0x11223344
} NVDLA_SCSV_EXTENSION_PACKER_ENUM;

#endif
